# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3febabb9009aa06714e25e3ec1774d78395a58c33aa1cfaf7761097a77820dfc1ec67fb0669906acf6bb3865e9c08fb9371adf64556a491d856dd08129cbf547

test:
  secret_key_base: eb54d38273da824af260dbb6ab6bfe543d03cdd5314f85bdf04854b79d28acc5b263da5d5d4c472685993e98743a92b4c1bac3aec2383ba820c18689d7e5d5a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
